name: liteproxy

networks:
  kong:
    driver: bridge
    name: kong-net

services:
  liteproxy:
    container_name: liteproxy-service
    image: "ckleest/liteproxy:latest"
    ports:
      - "8082:8082"
    networks:
      - kong
    environment:
      - GIN_MODE=release
    restart: always
    depends_on:
      - redis
    labels:
      - "liteproxy webservice"
      - "corsproxy webservice"

  redis:
    image: "redis:latest"
    container_name: liteproxy-redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - kong
    ports:
      - "6379:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
